package com.asya.weatherapp

import com.asya.weatherapp.ui.cityList.model.CityModel

object CityList {
    fun getCityList(): List<CityModel> {
        return ArrayList<CityModel>()
            .apply {
                add(
                    CityModel(
                        "Vienna"
                    )
                )
                add(
                    CityModel(
                        "Baku"
                    )
                )
                add(
                    CityModel(
                        "Brussels"
                    )
                )
                add(
                    CityModel(
                        "Sofia"
                    )
                )
                add(
                    CityModel(
                        "Prague"
                    )
                )
                add(
                    CityModel(
                        "Santo Domingo"
                    )
                )
                add(
                    CityModel(
                        "Paris"
                    )
                )
                add(
                    CityModel(
                        "Berlin"
                    )
                )
                add(
                    CityModel(
                        "Athens"
                    )
                )
                add(
                    CityModel(
                        "Budapest"
                    )
                )
                add(
                    CityModel(
                        "Dublin"
                    )
                )
                add(
                    CityModel(
                        "Tokyo"
                    )
                )
                add(
                    CityModel(
                        "Seoul"
                    )
                )
                add(
                    CityModel(
                        "Luxembourg"
                    )
                )
                add(
                    CityModel(
                        "Mexico City"
                    )
                )
                add(
                    CityModel(
                        "Amsterdam"
                    )
                )
                add(
                    CityModel(
                        "Mexico City"
                    )
                )
                add(
                    CityModel(
                        "Oslo"
                    )
                )
                add(
                    CityModel(
                        "Warsaw"
                    )
                )
                add(
                    CityModel(
                        "Lisbon"
                    )
                )
                add(
                    CityModel(
                        "Warsaw"
                    )
                )
                add(
                    CityModel(
                        "Moscow"
                    )
                )
                add(
                    CityModel(
                        "Madrid"
                    )
                )
                add(
                    CityModel(
                        "Stockholm"
                    )
                )
                add(
                    CityModel(
                        "Ankara"
                    )
                )
                add(
                    CityModel(
                        "Kiev"
                    )
                )
                add(
                    CityModel(
                        "London"
                    )
                )
                add(
                    CityModel(
                        "Washington DC"
                    )
                )
                add(
                    CityModel(
                        "Abu Dhabi"
                    )
                )
                add(
                    CityModel(
                        "Belgrade"
                    )
                )
                add(
                    CityModel(
                        "Singapore"
                    )
                )
                add(
                    CityModel(
                        "Colombo"
                    )
                )
            }
    }
}